apiVersion: v1
kind: Service
metadata:
  name: simple-angular-service
spec:
  type: LoadBalancer
  selector:
    app: simple-angular-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
